### ISSUE TITLE
TagBot not working

### ISSUE THREAD

**Issue by timholy** [bcbi/RetroCap.jl#56]
Version 2.1 is [out](https://github.com/JuliaRegistries/General/pull/67353) but not showing up on the releases page.

**Comment by DilumAluthge** [comment]
Looks like the workflow was disabled after 60 days of inactivity. I re-enabled the workflow and triggered a manual run.

**Comment by DilumAluthge** [comment]
Looks fixed now: https://github.com/JuliaRegistries/RetroCap.jl/releases/tag/v2.1.0
